# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: confpack.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63onfpack.proto\"\x86\x01\n\x0f\x43\x61rrierManifest\x12\x10\n\x08revision\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ncarrier_id\x18\x03 \x01(\r\x12\x1b\n\x13oldest_compat_modem\x18\x04 \x01(\t\x12\"\n\x08\x63onfseqs\x18\x05 \x03(\x0b\x32\x10.ConfseqFileInfo\"\x95\x01\n\x0f\x43onfseqFileInfo\x12\x12\n\nssid_group\x18\x01 \x01(\r\x12 \n\x18\x63onfseq_truncated_sha256\x18\x02 \x01(\x0c\x12\n\n\x02\x66\x33\x18\x03 \x01(\r\x12\n\n\x02\x66\x34\x18\x04 \x01(\x05\x12\x11\n\tblob_path\x18\x05 \x01(\t\x12\x10\n\x08platform\x18\x06 \x01(\r\x12\x0f\n\x07product\x18\x07 \x01(\r\"Z\n\x07\x43onfseq\x12\x10\n\x08revision\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x02\x66\x33\x18\x03 \x03(\x0b\x32\x08.m39a785\x12\x19\n\x08nv_items\x18\x04 \x03(\x0b\x32\x07.NvItem\">\n\x0bNvItemWrite\x12\x11\n\tstart_seq\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\r\n\x05value\x18\x03 \x01(\x04\"<\n\x06NvItem\x12\x14\n\x0cnv_item_hash\x18\x01 \x01(\r\x12\x1c\n\x06writes\x18\x02 \x03(\x0b\x32\x0c.NvItemWrite\"K\n\x07m39a708\x12\x0c\n\x02\x66\x31\x18\x01 \x01(\tH\x00\x12\x0c\n\x02\x66\x32\x18\x02 \x01(\x05H\x00\x12\x0c\n\x02\x66\x33\x18\x03 \x01(\x04H\x00\x12\x0c\n\x02\x66\x34\x18\x04 \x01(\x0cH\x00\x42\x08\n\x06oneof1\"C\n\x07m39a785\x12\n\n\x02\x66\x31\x18\x01 \x01(\r\x12\n\n\x02\x66\x32\x18\x02 \x01(\r\x12\n\n\x02\x66\x33\x18\x03 \x01(\r\x12\x14\n\x02\x66\x34\x18\x04 \x03(\x0b\x32\x08.m39a708')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'confpack_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CARRIERMANIFEST._serialized_start=19
  _CARRIERMANIFEST._serialized_end=153
  _CONFSEQFILEINFO._serialized_start=156
  _CONFSEQFILEINFO._serialized_end=305
  _CONFSEQ._serialized_start=307
  _CONFSEQ._serialized_end=397
  _NVITEMWRITE._serialized_start=399
  _NVITEMWRITE._serialized_end=461
  _NVITEM._serialized_start=463
  _NVITEM._serialized_end=523
  _M39A708._serialized_start=525
  _M39A708._serialized_end=600
  _M39A785._serialized_start=602
  _M39A785._serialized_end=669
# @@protoc_insertion_point(module_scope)
